# Generated by Django 5.1.3 on 2026-05-01 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa_app', '0002_user_middle_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeprofile',
            options={},
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='description',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='hire_date',
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='work_days',
            field=models.JSONField(blank=True, default=list, verbose_name='Рабочие дни (0=Пн ... 6=Вс)'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='work_end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Конец рабочего дня'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='work_start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Начало рабочего дня'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='experience_years',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='employees/'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='position',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, verbose_name='Логин'),
        ),
    ]
