# Generated by Codex on 2026-05-01

from django.db import migrations, models


def migrate_legacy_schedule_to_employee_profile(apps, schema_editor):
    EmployeeProfile = apps.get_model("spa_app", "EmployeeProfile")
    EmployeeSchedule = apps.get_model("spa_app", "EmployeeSchedule")

    for employee in EmployeeProfile.objects.all():
        if employee.work_days or employee.work_start_time or employee.work_end_time:
            continue

        schedules = list(
            EmployeeSchedule.objects.filter(employee_id=employee.id, is_active=True).order_by(
                "weekday",
                "start_time",
            )
        )
        if not schedules:
            continue

        time_pairs = {(schedule.start_time, schedule.end_time) for schedule in schedules}
        if len(time_pairs) != 1:
            continue

        employee.work_days = sorted({int(schedule.weekday) for schedule in schedules})
        employee.work_start_time = schedules[0].start_time
        employee.work_end_time = schedules[0].end_time
        employee.save(
            update_fields=["work_days", "work_start_time", "work_end_time"]
        )


class Migration(migrations.Migration):

    dependencies = [
        ("spa_app", "0003_alter_employeeprofile_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeprofile",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="hire_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RunPython(
            migrate_legacy_schedule_to_employee_profile,
            migrations.RunPython.noop,
        ),
    ]
