# Generated by Django 5.1.3 on 2026-05-18 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa_app', '0007_appointment_is_paid_appointment_paid_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_refunded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Наличные'), ('card', 'Карта')], max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('created', 'Создана'), ('confirmed', 'Подтверждена'), ('completed', 'Завершена'), ('failed', 'Завершена неуспешно'), ('cancelled', 'Отменена')], default='created', max_length=20),
        ),
        migrations.AlterField(
            model_name='review',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
