# Generated by Django 5.1.3 on 2026-05-18 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa_app', '0008_appointment_is_refunded_appointment_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
